SimpleMVC/Controllers/SimpleController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using SimpleMVC.Data;
using SimpleMVC.Models;
using SimpleMVC.ViewModels;

namespace SimpleMVC.Controllers
{
  
    public class SimpleController : Controller
    {
        // GET: SimpleController
        private List<Person>? persons;
        private List<Income>? incomes;
        private List<Spending>? spendings;
        private List<Saving> savings;
        private List<Fortune> fortune;

        //   public List<Person> Persons { get; set; } = new List<Person>();

        private readonly ApplicationDbContext db;

        public SimpleController(ApplicationDbContext db)
        {
            this.db = db;
        }



        public IActionResult Index(Osoba os)
        {
            var viewModel = new HomeViewModelOne
            {
                Imie = os.Imie,//HttpContext.User.Identity.Name,
                PrzychodStaly = db.PrzychodyStale.FirstOrDefault(x => x.Id == os.IdPrzychodStaly),
                PrzychodZmienny = db.PrzychodyZmienne.FirstOrDefault(x => x.Id == os.IdPrzychodZmienny),
                WydatekStaly = db.WydatkiStale.FirstOrDefault(x => x.Id == os.IdWydatekStaly),
                WydatekZmienny = db.WydatkiZmienne.FirstOrDefault(x => x.Id == os.IdWydatekZmienny),
                OszczednosciStale = db.OszczednosciStale.FirstOrDefault(x => x.Id == os.IdOszczednosciStale),
                OszczednosciZmienne = db.OszczednosciZmienne.FirstOrDefault(x => x.Id == os.IdOszczednosciZmienne),
                Majatek = db.Majatki.FirstOrDefault(x => x.Id == os.IdMajatek),
                Osoba = os // Tutaj zainicjalizuj obiekt Osoba
            };

            return View(viewModel);
        }
     /*   public IActionResult Index(Osoby os)
        {
            // SimpleExemple exemples = new SimpleExemple("trangle", 3.4f, 4.6f);
            persons = new List<Person>()
            {
                new Person() {Id = 1, FirstName = "Jan", LastName = "Kowalski", Age = 35, IdIncome = 1, IdSpending = 1, IdSavings=1},
                new Person() {Id = 2, FirstName = "Ewa", LastName = "Farna", Age = 54, IdIncome = 2, IdSpending = 2, IdSavings=2},
                new Person() {Id = 3, FirstName = "Stanisław", LastName = "Kamiński", Age = 70, IdIncome = 3, IdSpending = 3, IdSavings = 3},
                new Person() {Id = 4, FirstName = "Janina", LastName = "Kowalskia", Age = 20, IdIncome = 4, IdSpending = 4, IdSavings = 4},
                new Person() {Id = 5, FirstName = "Jurek", LastName = "Nowak", Age = 45, IdIncome = 5, IdSpending = 5, IdSavings = 5}

            };

            incomes = new List<Income>()
            {
                new Income() {Id = 1, Date = DateTime.Now, Wyplata = 3500, DodatkowaPraca = 500, Renta = 0, Wynajem = 0},
                new Income() {Id = 2, Date = DateTime.UtcNow,  Wyplata = 10000, DodatkowaPraca = 5000, Renta = 0, Wynajem  = 0},
                new Income() {Id = 3, Date = DateTime.Now, Wyplata = 0, DodatkowaPraca = 0, Renta = 2500, Wynajem = 0},
                new Income() {Id = 4, Date = DateTime.UtcNow, Wyplata = 6500, DodatkowaPraca = 600, Renta = 0, Wynajem = 0},
                new Income() {Id = 5, Date = DateTime.Now, Wyplata = 5500, DodatkowaPraca = 700, Renta = 0, Wynajem = 0}
            };

            spendings = new List<Spending>()
            {
                new Spending() {Id = 1, Rachunki = 1500, Lekarstwa = 0, Jedzenie = 800, Wakacje = 0, Kredyty = 500, Nieoczekiwane = 0, Date = DateTime.Now },
                new Spending() {Id = 2, Rachunki = 2000, Lekarstwa = 0, Jedzenie = 2000, Wakacje = 5000, Kredyty = 500, Nieoczekiwane = 500, Date = DateTime.Now },
                new Spending() {Id = 3, Rachunki = 600, Lekarstwa = 500, Jedzenie = 600, Wakacje = 0, Kredyty = 0, Nieoczekiwane = 500, Date = DateTime.Now },
                new Spending() {Id = 4, Rachunki = 800, Lekarstwa = 200, Jedzenie = 800, Wakacje = 2500, Kredyty = 700, Nieoczekiwane = 600, Date = DateTime.Now },
                new Spending() {Id = 5, Rachunki = 1000, Lekarstwa = 0, Jedzenie = 1000, Wakacje = 2000, Kredyty = 500, Nieoczekiwane = 0, Date = DateTime.Now },


            };

            savings = new List<Saving>()
            {
                new Saving() {Id = 1,  Inwestycje = 0, Lokaty = 0, Obligacje = 600, Kieszonkowe = 600, NaPrzyszłość = 0, Date = DateTime.Now },
                new Saving() {Id = 2,  Inwestycje = 1000, Lokaty = 500, Obligacje = 500, Kieszonkowe = 2000, NaPrzyszłość = 1000, Date = DateTime.Now },
                new Saving() {Id = 3,  Inwestycje = 0, Lokaty = 0, Obligacje = 0, Kieszonkowe = 0, NaPrzyszłość = 300, Date = DateTime.Now },
                new Saving() {Id = 4,  Inwestycje = 500, Lokaty = 0, Obligacje = 500, Kieszonkowe = 500, NaPrzyszłość = 0, Date = DateTime.Now },
                new Saving() {Id = 5,  Inwestycje = 200, Lokaty = 300, Obligacje = 300, Kieszonkowe = 500, NaPrzyszłość = 400, Date = DateTime.Now },



            };

            fortune = new List<Fortune>()
            {
                new Fortune() {Id = 1,  Ruchomosc= 10000, Nieruchomosci = 500000, MetaleIKamienie = 200, PapieryWartosciowe = 0, Gotowka = 40000, Date = DateTime.Now },
                new Fortune() {Id = 2,  Ruchomosc= 20000, Nieruchomosci = 400000, MetaleIKamienie = 800, PapieryWartosciowe = 1000, Gotowka = 30000, Date = DateTime.Now },
                new Fortune() {Id = 3,  Ruchomosc= 30000, Nieruchomosci = 300000, MetaleIKamienie = 0, PapieryWartosciowe = 0, Gotowka = 15000, Date = DateTime.Now },
                new Fortune() {Id = 4,  Ruchomosc= 10000, Nieruchomosci = 300000, MetaleIKamienie = 300, PapieryWartosciowe = 0, Gotowka = 100000, Date = DateTime.Now },
                new Fortune() {Id = 5,  Ruchomosc= 20000, Nieruchomosci = 600000, MetaleIKamienie = 0, PapieryWartosciowe = 0, Gotowka = 20000, Date = DateTime.Now },



            };

            //     var modele = new Tuple<Person, Income, Spending>(Persons, incomes, spendings);
            var models = new List<ModelComplex>();

            // Iteruj przez każdą osobę, przypisz jej odpowiedni dochód i wydatek
            foreach (var person in persons)
            {
                var model = new ModelComplex
                {
                    Person = person,
                    Income = incomes.FirstOrDefault(i => i.Id == person.IdIncome),
                    Spending = spendings.FirstOrDefault(s => s.Id == person.IdSpending),
                    Saving=savings.FirstOrDefault(sa=>sa.Id==person.IdSavings),
                    Fortune = fortune.FirstOrDefault(sa => sa.Id == person.IdSavings)

                };

                models.Add(model);
            }

            return View(models);
        }*/

        // GET:SimpleController/Details/5

        public IActionResult Details(int id)
        {
            if (id == null)
                return BadRequest("Nie ma takiej osoby w bazie");

            // var oneperson = persons.
            Person persons = new Person();
            if (ModelState.IsValid && persons.Id == id)
            {
                return View(persons.Id);
            }
            else
                return RedirectToAction("Index");
        }

        // GET: SimpleController/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SimpleController/Create

        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SimpleController/Edit/5
        public IActionResult Edit(int id)
        {
            return View();
        }

        // POST: SimpleController/Edit/5

        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SimpleController/Delete/5
        public IActionResult Delete(int id)
        {
            return View();
        }

        // POST: SimpleController/Delete/5

        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

SimpleMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SEJFer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SimpleMVC.styles.css" asp-append-version="true" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-toggleable-md navbar-dark  mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Account" asp-action="StronaLogowania"> SEJFer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-md-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="User">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Simple" asp-action="">Majątek</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Raport" asp-action="">Zestawienia</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Profilev1" asp-action="">Profil finansowy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="About" asp-action="">O nas</a>
                        </li>

                        
                       
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Logout">Wylogowanie</a>
                            </li>
                        
                        
                       
                        
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
           <p> &copy; 2024 - SEJFer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Polityka prywatności</a></p>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://kit.fontawesome.com/5b42df6bf7.js" crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>